# Generated by Django 2.2.3 on 2019-09-24 11:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Clearcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_date', models.DateField()),
                ('area', models.FloatField()),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('mpoly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearcuts.Zone')),
            ],
        ),
    ]
