# Generated by Django 2.2.3 on 2020-07-16 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearcut',
            name='image_date_current',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 9, 3, 56, 706157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clearcut',
            name='image_date_previous',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 9, 3, 56, 706131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='tile_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 9, 3, 56, 706913, tzinfo=utc)),
        ),
    ]
