# Generated by Django 3.1 on 2020-09-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0002_clearcut_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearcut',
            name='preview_current_path',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='preview_previous_path',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
