# Generated by Django 2.2.3 on 2020-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0002_tileinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileinformation',
            name='tile_metadata_hash',
            field=models.CharField(blank=True, default=0, max_length=32, null=True),
        ),
    ]
