# Generated by Django 3.1 on 2020-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0003_auto_20200918_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='crs',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
