# Generated by Django 2.2.3 on 2020-03-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0003_auto_20200224_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileinformation',
            name='model_tiff_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='source_b04_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='source_b08_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='source_tci_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
