# Generated by Django 2.2.3 on 2020-03-24 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0004_auto_20200324_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileinformation',
            name='source_b8a_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='source_b11_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='source_b12_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='tile_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='source_clouds_location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='tile_name',
            field=models.CharField(max_length=7),
        ),

    ]

