# Generated by Django 2.2.3 on 2020-05-18 07:48
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0004_update_tileinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearcut',
            old_name='image_date',
            new_name='image_date_current'
        ),
        migrations.AlterField(
            model_name='clearcut',
            name='image_date_current',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='image_date_previous',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='forest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='clouds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='tile_index',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
