# Generated by Django 2.2.3 on 2020-05-18 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0004_update_tileinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearcut',
            name='image_date',
        ),
        migrations.AddField(
            model_name='clearcut',
            name='forest',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='image_date_0',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='image_date_1',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='tile_index',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
