# Generated by Django 2.2.14 on 2020-07-20 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0006_01'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearcut',
            name='image_date_0',
        ),
        migrations.RemoveField(
            model_name='clearcut',
            name='image_date_1',
        ),
        migrations.AddField(
            model_name='clearcut',
            name='clouds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='image_date_current',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 6, 57, 9, 251236, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='image_date_previous',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 6, 57, 9, 251198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clearcut',
            name='forest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='model_tiff_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='source_b04_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='source_b08_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='source_b11_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='source_b12_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='source_b8a_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='source_clouds_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='source_tci_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='tile_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 6, 57, 9, 252519, tzinfo=utc)),
        ),
    ]
