# Generated by Django 2.2.3 on 2020-07-14 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0006_auto_20200714_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearcut',
            name='image_date_0',
        ),
        migrations.RemoveField(
            model_name='clearcut',
            name='image_date_1',
        ),
        migrations.AddField(
            model_name='clearcut',
            name='clouds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='image_date_current',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 11, 35, 17, 670179, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='image_date_previous',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 11, 35, 17, 670132, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='clearcut',
            name='not_forest',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clearcut',
            name='forest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='tile_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 14, 11, 35, 17, 671356, tzinfo=utc)),
        ),
    ]
