# Generated by Django 2.2.14 on 2020-07-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileinformation',
            name='is_converted',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='is_downloaded',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='is_predicted',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='is_prepared',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tileinformation',
            name='is_uploaded',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runupdatetask',
            name='tile_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_update_task', to='clearcuts.Tile'),
        ),
        migrations.AlterField(
            model_name='tileinformation',
            name='tile_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_information', to='clearcuts.Tile'),
        ),
    ]
