# Generated by Django 2.2.14 on 2020-07-31 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0008_auto_20200726_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='tile_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tile_zones', to='clearcuts.Tile'),
        ),
    ]
