# Generated by Django 2.2.14 on 2020-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0009_zone_tile_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='tile_index',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
