# Generated by Django 2.2.14 on 2020-08-15 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clearcuts', '0010_update_tile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceJp2Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_date', models.DateField()),
                ('tile_uri', models.URLField(unique=True)),
                ('cloud_coverage', models.FloatField(default=0)),
                ('nodata_pixel', models.FloatField(default=0)),
                ('source_tci_location', models.URLField(blank=True, null=True)),
                ('source_b04_location', models.URLField(blank=True, null=True)),
                ('source_b08_location', models.URLField(blank=True, null=True)),
                ('source_b8a_location', models.URLField(blank=True, null=True)),
                ('source_b11_location', models.URLField(blank=True, null=True)),
                ('source_b12_location', models.URLField(blank=True, null=True)),
                ('source_clouds_location', models.URLField(blank=True, null=True)),
                ('is_downloaded', models.SmallIntegerField(default=0)),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jp2_images', to='clearcuts.Tile')),
            ],
            options={
                'unique_together': {('tile', 'image_date')},
            },
        ),
    ]
