# Generated by Django 3.1 on 2020-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_sourcejp2images_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcejp2images',
            name='source_tci_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sourcejp2images',
            name='tile_uri',
            field=models.URLField(null=True),
        ),
    ]
