# Generated by Django 3.1 on 2020-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_auto_20200925_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcejp2images',
            name='is_converted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
