# Generated by Django 2.2.3 on 2020-05-12 20:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_name', models.CharField(max_length=7)),
                ('tile_location', models.CharField(blank=True, max_length=60, null=True)),
                ('source_tci_location', models.CharField(blank=True, max_length=60, null=True)),
                ('source_b04_location', models.CharField(blank=True, max_length=60, null=True)),
                ('source_b08_location', models.CharField(blank=True, max_length=60, null=True)),
                ('source_b8a_location', models.CharField(blank=True, max_length=60, null=True)),
                ('source_b11_location', models.CharField(blank=True, max_length=60, null=True)),
                ('source_b12_location', models.CharField(blank=True, max_length=60, null=True)),
                ('model_tiff_location', models.CharField(blank=True, max_length=60, null=True)),
                ('tile_metadata_hash', models.CharField(blank=True, default=0, max_length=32, null=True)),
                ('cloud_coverage', models.FloatField(default=0)),
                ('mapbox_tile_id', models.CharField(blank=True, max_length=32, null=True)),
                ('mapbox_tile_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mapbox_tile_layer', models.CharField(blank=True, max_length=32, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Clearcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_date', models.DateField()),
                ('area', models.FloatField()),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('mpoly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearcuts.Zone')),
            ],
        ),
    ]
