# Generated by Django 2.2.3 on 2020-05-18 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcuts', '0003_auto_20200518_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileinformation',
            name='tile_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
